version: "3.4"

services:
  north_client:
    build:
      context: .
      target: app_node
      network: host
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./dbbackup:/app/dbbackup
    ports:
      - "80:9000"
